// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Order_Service.Data;

#nullable disable

namespace Order_Service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Order_Service.Models.Order", b =>
            {
                b.Property<Guid>("OrderId").HasColumnType("uuid");
                b.Property<string>("CancellationReason").HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("CustomerId").IsRequired().HasColumnType("text");
                b.Property<string>("DeliveryAddress").IsRequired().HasColumnType("text");
                b.Property<string>("DeliveryAgentId").HasColumnType("text");
                b.Property<decimal>("Discount").HasColumnType("decimal(18,2)");
                b.Property<decimal>("FinalAmount").HasColumnType("decimal(18,2)");
                b.Property<string>("ModeOfPayment").IsRequired().HasColumnType("text");
                b.Property<string>("Notes").HasColumnType("text");
                b.Property<Guid>("RestaurantId").HasColumnType("uuid");
                b.Property<int>("Status").HasColumnType("integer");
                b.Property<decimal>("TotalAmount").HasColumnType("decimal(18,2)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("OrderId");
                b.ToTable("Orders");
            });

            modelBuilder.Entity("Order_Service.Models.OrderItem", b =>
            {
                b.Property<Guid>("OrderItemId").HasColumnType("uuid");
                b.Property<string>("Customization").HasColumnType("text");
                b.Property<Guid>("MenuItemId").HasColumnType("uuid");
                b.Property<string>("Name").IsRequired().HasColumnType("text");
                b.Property<Guid>("OrderId").HasColumnType("uuid");
                b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
                b.Property<int>("Quantity").HasColumnType("integer");
                b.HasKey("OrderItemId");
                b.HasIndex("OrderId");
                b.ToTable("OrderItems");
            });

            modelBuilder.Entity("Order_Service.Models.OrderItem", b =>
            {
                b.HasOne("Order_Service.Models.Order", "Order")
                    .WithMany("Items")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Order");
            });

            modelBuilder.Entity("Order_Service.Models.Order", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
        }
    }
}
